### PR TITLE
Bug 1721597: Adding ability to remove cluster scoped resources on deletion (#49)

### PR DESCRIPTION
**Pull request by shawn-hurley**
* adding finalizer to TSB resource which will set the correct state for the resources to be removed.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
has this PR merged into master branch already?  the referenced BZ does not appear to have a clone for the master branch for QE to verify against that stream as well.  my bias is that we fix and verify in master before we pick back to support streams moving forward.

**Comment by shawn-hurley** [comment]
@derekwaynecarr I have updated the BZ's to correct this error and everything should be looking better.

**Comment by shawn-hurley** [comment]
/hold

Waiting on soak and verification in the master branch

**Comment by eparis** [comment]
Looks like the 4.2 bug failed QA. You likely need to contact QA directly.

**Comment by eparis** [comment]
looks like 4.2 QE is still ongoing. weeeee

**Comment by eparis** [comment]
/bugzilla refresh
Looks like the 4.2/master PR failed QE validation. That will need to be reworked and this PR updated to include whatever is needed to make progress.

**Comment by bparees** [comment]
/bugzilla refresh

@shawn-hurley needs an lgtm and we can try to land it this z-stream....

**Pull request merged**
