### PR TITLE
Bug 1800710: pin CI dependencies

### PR DESCRIPTION
**Pull request by fabianvf**

### CODE REVIEW

**Comment by jmrodri** [comment]
Overrode the tests since they all failed with the changes that this PR is attempting to fix:
```
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xB8TNB/python-string-utils/
You are using pip version 8.1.2, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
error: build error: running 'pip install -U setuptools  &&...0.9.0'  && pip install -U requests' failed with exit code 1
```

**Comment by sdodson** [comment]
/hold
@fabianvf @jmrodri PTAL at the failing tests

**Comment by jmrodri** [comment]
FYI we have to override the tests because this PR is the thing that is trying to fix all of those tests.

**Comment by sdodson** [comment]
> FYI we have to override the tests because this PR is the thing that is trying to fix all of those tests.

That seems odd, if this PR fixes those tests why didn't it pass?

**Pull request merged**
