### PR TITLE
Operator SDK Alignment

### PR DESCRIPTION
**Pull request by djzager**
This updates the template service broker operator project to look like an `operator-sdk` project looks like.

### CODE REVIEW

**Comment by djzager** [comment]
I'm expecting this PR to fail prow. I will make a attach the prow updates to this PR so that we can get green before merge.

This intentionally does not include the molecule or any test playbook.

**Review by eriknelson — CHANGES_REQUESTED** [review]
We should update the readme with some info about the make targets and the requirement for `IMAGE` to be there. I didn't add IMAGE with make deploy and ended up in a corrupt state that I manually needed to get myself out of.

Once I used the correct IMAGE though, everything came up like a charm.

**Review by eriknelson — APPROVED** [review]

**Comment by sosiouxme** [comment]
please inform ART before moving dockerfile like this. it breaks the whole build.
https://mojo.redhat.com/docs/DOC-1178565#jive_content_id_How_should_I_coordinate_changes_to_existing_builds_with_ART

**Comment by djzager** [comment]
@sosiouxme Apologies for missing that. Had tried updating the ticket https://jira.coreos.com/browse/ART-430 but I see now that was not correct. Will not happen again.

**Pull request merged**
