### PR TITLE
Bug 1826396: OWNERS: update reviewers/approvers; add component

### PR DESCRIPTION
**Pull request by joelanford**
- Removed reviewers and approvers no longer working on this project
- Added joelanford and camilamacedo86
- Added `component: "Service Broker"`

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by shawn-hurley** [comment]
/override ci/prow/operator-molecule-e2e 
/override ci/prow/operator-molecule-olm-e2e 

The service catalog is removed in master, these test will always fail.

**Comment by petr-muller** [comment]
/hold

This PR accumulated the `This SHA and context has reached the maximum number of statuses.`-level of failed statuses and Prow cannot report the status to make this context green for Tide to merge it.

I suggest to either push a new commit (just an amend to make a SHA different), and re-lgtm (and possibly re-override the tests because https://github.com/openshift/template-service-broker-operator/pull/94#issuecomment-620523315), or just merge-button this.

**Comment by stevekuznetsov** [comment]
/hold

This is hitting issues with the reporting limit again. I would strongly suggest the group lead or team lead to just merge this with the button. The amount of CI resources and human process that has been expended on a trivial OWNERS file change is very surprising.

**Comment by jmrodri** [comment]
@stevekuznetsov there is a problem with the repo's CI so we were using this PR to help debug it.

**Pull request merged**
