### PR TITLE
Bug 1793368: apply permission fix in the etc/pwd [release-4.2]

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
- Fix permission for `/etc/passwd`

Requires: #91 ( to fix the build )

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/restest 

PS: Ci issue `error: could not resolve inputs: could not determine inputs for step [input:ansible_operator]: could not resolve base image: imagestreamtags.image.openshift.io "4.0" not found`

**Comment by camilamacedo86** [comment]
/test lint
/test operator-molecule-olm-e2e
/test operator-molecule-e2e
/test images

PS: Ci issue `error: could not resolve inputs: could not determine inputs for step [input:ansible_operator]: could not resolve base image: imagestreamtags.image.openshift.io "4.0" not found`

**Comment by jmrodri** [comment]
We do not want to remove the /etc/passwd from the CI dockerfile. Closing this because the CVE was fixed in the ansible-operator already.

```
[jesusr@transam zeus-operator{master}]$ docker run -it --entrypoint=/bin/bash  registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-template-service-broker-operator:v4.2.31-202004250432
Unable to find image 'registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-template-service-broker-operator:v4.2.31-202004250432' locally
v4.2.31-202004250432: Pulling from rh-osbs/openshift-ose-template-service-broker-operator
23302e52b49d: Already exists 
cf5693de4d3c: Already exists 
0bdf97977791: Already exists 
e4d3fc95f142: Pull complete 
dcd03dae33bf: Pull complete 
74d6a7abd18f: Pull complete 
Digest: sha256:fc6c3fc35daab80b1fdefc9fc7d8ddd8a36c1e2160ffc5475e36a6e52dd6e549
Status: Downloaded newer image for registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-template-service-broker-operator:v4.2.31-202004250432
bash-4.2$ ls -l /etc/passwd
-rw-r--r--. 1 root root 750 Apr 25 05:30 /etc/passwd
```

**Pull request closed without merging**
