### PR TITLE
Bug 1800707: pin CI dependencies

### PR DESCRIPTION
**Pull request by fabianvf**

### CODE REVIEW

**Comment by shawn-hurley** [comment]
/hold

Why are these failing

**Comment by jmrodri** [comment]
We need to override the images and lint because this PR is done to fix those

/override ci/prow/images
/override ci/prow/lint

**Comment by shawn-hurley** [comment]
/hold

@jmrodri @joelanford

**Comment by shawn-hurley** [comment]
Image testing is failing, seems like we can't even build this

**Pull request merged**
