### PR TITLE
Bring Erik's stuff in

### PR DESCRIPTION
**Pull request by djzager**

### CODE REVIEW

**Comment by djzager** [comment]
@jwmatthews @djwhatle

**Comment by djzager** [comment]
Adding @eriknelson in case he wants to see what is happening.

**Review by jmrodri — APPROVED** [review]
ACK

**Comment by djwhatle** [comment]
+1 for @eriknelson's stuff

**Comment by jmrodri** [comment]
Can we change the settings of the project to remove the create merge commit option :) makes for ugly git histories IMO

**Comment by djzager** [comment]
I think @tsanders-rh may need to give us more power over this repo to modify the settings.

**Pull request merged**
